// Generated by prisma-generator-tsrpc v1.0.7

/* Enum 消费类型 */
export enum UserFileConsumeType {
    MEMBER,
    RESOURCE_PACKAGE,
    OTHER
}

/* Enum 用户记录来源 */
export enum UserRecordSource {
    Promoter,
    Order,
    System,
    Activity,
    Other
}

/* Enum 用户记录类型 */
export enum UserRecordType {
    Alliance,
    Withdraw,
    ResourcePackage,
    Member,
    Other
}

/* Model 用户 */
export interface User {
    /* ID 主键 */
    id: number;
    /* 昵称 */
    nickname: string;
    /* 头像 */
    avatar?: string;
    /* 手机号 */
    phone?: string;
    /* 手机区号 */
    phoneCode?: string;
    /* 手机是否验证 */
    phoneVerififedAt?: Date;
    /* 是否会员 */
    isMember: boolean;
    /* 会员等级 */
    memberLevel: number;
    /* 会员过期时间 */
    memberExpiredAt?: Date;
    /* 会员开通时间 */
    memberStartedAt?: Date;
    /* 登陆 IP */
    loginIp?: string;
    /* 登陆时间 */
    loginAt?: Date;
    /* 注册 IP */
    registerIp?: string;
    /* 注册时间 */
    registerAt?: Date;
    /* 注册渠道 */
    registerChannel?: string;
    /* 邀请人 ID */
    inviterId?: number;
    /* 邀请活动 ID */
    inviteActivityId?: number;
    /* 是否开通推广联盟 */
    isPromoter: boolean;
    /* 推广联盟会员订单分成 */
    promoterOrderDivide?: number;
    /* 推广联盟资源包订单分成 */
    promoterPackageDivide?: number;
    /* 推广联盟其他类型订单分成 */
    promoterOtherDivide?: number;
    /* 总提成 */
    totalDivide?: number;
    /* 已提现 */
    withdrawedDivide?: number;
    /* 未提现 */
    unwithdrawDivide?: number;
    /* 已结算提成 */
    settledDivide?: number;
    /* 未结算提成 */
    unsettledDivide?: number;
    /* 会员天数奖励 */
    memberDayReward?: number;
    /* 资源包次数奖励 */
    packageCountReward?: number;
    /* 提现方式 */
    withdrawType?: string;
    /* 提现账号 */
    withdrawAccount?: string;
    /* 是否封禁 */
    isBanned: boolean;
    /* 封禁原因 */
    bannedReason?: string;
    /* 封禁时间 */
    bannedAt?: Date;
    /* 封禁过期时间 */
    bannedExpiredAt?: Date;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 删除时间 */
    deletedAt?: Date;
    /* 文件 */
    files: UserFile[];
    /* 批量文件处理记录 */
    batchFiles: UserBatchFile[];
    /* 资源包 */
    resourcePackages: UserResourcePackage[];
    /* 用户记录 */
    records: UserRecord[];
}

/* Model 用户文件 */
export interface UserFile {
    /* ID 主键 */
    id: number;
    /* 文件名 */
    fileName?: string;
    /* 文件大小 */
    fileSize?: number;
    /* 文件尺寸 [width,height] */
    fileDimension: number[];
    /* 文件 MD5 */
    fileMd5?: string;
    /* 文件路径 */
    filePath?: string;
    /* 结果路径 */
    resultPath?: string;
    /* 结果大小 */
    resultSize?: number;
    /* 结果尺寸 [width,height] */
    resultDimension: number[];
    /* 结果 MD5 */
    resultMd5?: string;
    /* 结果缩略图路径 */
    thumbnailResultPath?: string;
    /* 结果缩略图大小 */
    thumbnailResultSize?: number;
    /* 结果缩略图尺寸 [width,height] */
    thumbnailResultDimension: number[];
    /* 结果缩略图 MD5 */
    thumbnailResultMd5?: string;
    /* 缩略图路径 */
    thumbnailPath?: string;
    /* 缩略图大小 */
    thumbnailSize?: number;
    /* 缩略图尺寸 [width,height] */
    thumbnailDimension: number[];
    /* 缩略图 MD5 */
    thumbnailMd5?: string;
    /* 任务状态 */
    taskStatus?: string;
    /* 任务重试次数 */
    taskRetryCount?: number;
    /* 任务错误信息 */
    taskError?: string;
    /* 任务最近一次启动时间 */
    taskLastStartedAt?: Date;
    /* 任务最近一次数据汇报时间 */
    taskLastReportedAt?: Date;
    /* 任务人脸数据 */
    taskFaceData?: any;
    /* 任务类型 */
    taskType?: string;
    /* 原始数据是否删除 */
    isOriginalFileDeleted?: boolean;
    /* 原始数据删除时间 */
    originalFileDeletedAt?: Date;
    /* 是否来自小程序上传 */
    isFromMiniProgram?: boolean;
    /* 是否来自应用上传 */
    isFromApp?: boolean;
    /* 是否来自桌面端上传 */
    isFromDesktop?: boolean;
    /* 分享 短Key */
    shareShortKey?: string;
    /* 分享查看次数 */
    shareViewCount?: number;
    /* 分享下载次数 */
    shareDownloadCount?: number;
    /* 是否已经消费 */
    isConsumed?: boolean;
    /* 消费类型 */
    consumeType?: UserFileConsumeType;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 删除时间 */
    deletedAt?: Date;
    /* 用户 */
    user?: User;
    /* 用户 ID */
    userId?: number;
    /* 批量执行 */
    batch?: UserBatchFile;
    /* 批量执行 ID */
    batchId?: number;
}

/* Model 用户批量文件处理记录 */
export interface UserBatchFile {
    /* ID 主键 */
    id: number;
    /* 总文件 */
    total?: number;
    /* 已完成文件 */
    completed?: number;
    /* 失败的文件 */
    failed?: number;
    /* 总大小 */
    totalSize?: number;
    /* 压缩包路径 */
    zipPath?: string;
    /* 压缩包大小 */
    zipSize?: number;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 删除时间 */
    deletedAt?: Date;
    /* 文件 */
    files: UserFile[];
    /* 用户 */
    user?: User;
    /* 用户 ID */
    userId?: number;
}

/* Model 用户资源包 */
export interface UserResourcePackage {
    /* ID 主键 */
    id: number;
    /* 总次数 */
    total?: number;
    /* 已使用次数 */
    used?: number;
    /* 上一次消费时间 */
    lastUsedAt?: Date;
    /* 来源 */
    source?: string;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 删除时间 */
    deletedAt?: Date;
    /* 用户 */
    user?: User;
    /* 用户 ID */
    userId?: number;
}

/* Model 用户记录 */
export interface UserRecord {
    /* ID 主键 */
    id: number;
    /* 来源 */
    source: UserRecordSource;
    /* 类型 */
    type: UserRecordType;
    /* 具体数据 */
    data?: any;
    /* 备注 */
    remark?: string;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 删除时间 */
    deletedAt?: Date;
    /* 用户 */
    user?: User;
    /* 用户 ID */
    userId?: number;
}